project_id = "wxvsteaayxgygihpshoz"

[functions.sitemap]
verify_jwt = false

[functions.fetch-team-stats]
verify_jwt = false

[functions.update-team-stats-scheduled]
verify_jwt = false

[functions.send-subscription-confirmation]
verify_jwt = false

[functions.fetch-team-logo]
verify_jwt = false

[functions.fetch-match-details]
verify_jwt = false

[functions.social-webhook]
verify_jwt = false

[functions.goal-alerts]
verify_jwt = false

[functions.google-indexing]
verify_jwt = false

[functions.fetch-live-scores]
verify_jwt = false

[functions.fetch-sports-streams]
verify_jwt = false

[functions.fetch-highlights]
verify_jwt = false

[functions.fetch-clean-sports]
verify_jwt = false

[functions.proxy-stream]
verify_jwt = false
