project_id = "wxvsteaayxgygihpshoz"

[functions.scrape-article]
verify_jwt = false

[functions.fetch-highlights]
verify_jwt = false

[functions.fetch-match-details]
verify_jwt = false

[functions.fetch-team-logo]
verify_jwt = false

[functions.social-webhook]
verify_jwt = false

[functions.goal-alerts]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.scrape-news]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.sync-matches]
verify_jwt = false
